fix: optimizacion de codigo y mostrar coordina en el modal, en el per…
UNICAH-ICC-SAP/GestionPracticasWeb pull request #35
Opened 2024-12-10 19:18 UTC by dgudiel-oss

…filDocente

10/12: [FEATURE|BUGFIX] Optimización en el código y mostrar coordina en el modal, en perfilDocente.

UNICAH-ICC-SAP/GestionPracticasWeb/issues/18

2024-12-12 06:40 UTC, Acalix-unicah requested changes
Atienda los cambios de cada comentario, siga los estándares de escritura en React y las reglas de composición.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/estadoTerna/index.tsx
> -                <p>No tienes ternas donde seas coordinador.</p>
Implementar el componente que construyo pero para datos en blanco.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/estadoTerna/index.tsx
> +                <p>No tienes ternas donde seas {titulo.toLowerCase()}.</p>
Mismo caso del comentario anterior.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/estadoTerna/index.tsx
> +    const DetalleTerna = (titulo: string, detalle: AlumnoInfo[]) => (
Siga el estándar de creación de componentes para React, no lo cree en variables sino como archivo reutilizable.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/terna/index.tsx
>  type AlumnoInfo = {
El Type declarado en el namespace es diferente? si no es diferente implementar el typo definido en el namespace.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/terna/index.tsx
> +    const DetalleTerna = (titulo: string, detalle: AlumnoInfo[]) => (
Siga el comentario donde menciono la creación de archivos para cada componente de manera que sean reutilizables. esto es duplicidad de código.

2024-12-12 06:40 UTC, Acalix-unicah commented on src/pages/perfilDocente/terna/index.tsx
> +                <ModalBody style={{ fontSize: '15px' }}>
La aplicación de estilos debe ser desde la hoja CSS.

2024-12-13 15:29 UTC, dgudiel-oss commented
Se atendió los cambios solicitados
-Se reutilizo el componente Tables, el cual se le agrego un titulo ya que se tiene que mostrar un titulo donde el docente es "Coordinador de terna" y "Miembro de terna"
-Se hizo la modificación sobre los datos en blanco que utiliza la función de NotFound el cual mostrara el mensaje de "No se encontró información"
-Creación de la hoja de estilos para el modal

2024-12-22 16:04 UTC, Acalix-unicah approved these changes
Aprobado

2024-12-22 17:07 UTC, Acalix-unicah approved these changes
Realizar mejoras de codigo

2024-12-22 17:07 UTC, merged