fix: creacion funcional de las ternas y actualizaciones en store
UNICAH-ICC-SAP/GestionPracticasWeb pull request #37
Opened 2024-12-12 23:48 UTC by Bryan1129

##.##: [FEATURE|BUGFIX] Creacion de ternas funcional y mejoras en el store y en otros apartados del proyecto.

UNICAH-ICC-SAP/GestionPracticasWeb/issues/8

2024-12-13 05:38 UTC, Acalix-unicah requested changes
Atienda los cambios.

2024-12-13 05:38 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +                await dispatch(FetcherAlumnos.saveDataAlumno(paramsAlumno));
No necesita hacer un await del dispatch, el ya implementa un await.

2024-12-13 05:38 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +            console.log("No hay datos de alumno por guardar");
Archivos TSX no deben tener console.log o console.error.

2024-12-13 05:38 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +            window.location.reload();
Hay un action que limpia el store y uno que redirige al step 1.

2024-12-13 05:38 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +                        <CardSubtitle style={{ display: "flex", width: '75%', justifyContent: 'center', flexDirection: 'column' }} className="mb-2 text-muted" tag="div">
Los estilos deben ser implementados con clases de botstrap o con hojas de estilo CSS.

2024-12-13 05:38 UTC, Acalix-unicah commented on src/store/slices/alumnos/_reducers.ts
>      addCase(Action.cleanStore, (state) => ({
Este es el action que limpia el store.

2024-12-13 17:46 UTC, Bryan1129 commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +                await dispatch(FetcherAlumnos.saveDataAlumno(paramsAlumno));
Ya quite los await, y ya lo deje optimizado.

2024-12-13 17:48 UTC, Bryan1129 commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +            console.log("No hay datos de alumno por guardar");
Cambie los console log, y aplique el mismo sistema de alertas utilizado al guardar las ternas, pues ahora en caso de errores se utilizara ese sistema.

2024-12-13 17:51 UTC, Bryan1129 commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +            window.location.reload();
Ok con respecto a esta accion, probe usar el metodo que me recomendo que limpia el store, y no lo hace, solo una cantidad de datos, y ahorita con el cleanUserData, me limpia los campos, y luego con el redireccionamiento a la pagina inicial utilizo la accion del step1 para redigirir al principio, y cancelo el step2 y el resuemen, porque si no los hago asi, me salen todos los apartados en una sola pagina y se ve feo.

2024-12-13 17:52 UTC, Bryan1129 commented on src/pages/admin/crearTernas/creacionTernas/resumen.tsx
> +                        <CardSubtitle style={{ display: "flex", width: '75%', justifyContent: 'center', flexDirection: 'column' }} className="mb-2 text-muted" tag="div">
Ya aplique los estilos en la hoja de estilos de crear ternas y ya esta actualizado eso.

2024-12-13 17:52 UTC, Bryan1129 commented on src/store/slices/alumnos/_reducers.ts
>      addCase(Action.cleanStore, (state) => ({
La accion no funciono, no los limpia, necesito limpiar todo en general, asi que decidi seguir usando la misma accion.

2024-12-13 17:54 UTC, Bryan1129 commented
Aplique todos los cambios, solo con el de redireccionamiento tengo dudas, pero es la unica manera en la que me cumple el proceso, ya que si lo hago con algun metodo, me pierde la informacion y no se me guarda, espero que todo este bien.

2024-12-22 16:50 UTC, Acalix-unicah approved these changes
Realizar mejoras de codigo

2024-12-22 17:03 UTC, Acalix-unicah approved these changes
Realizar mejoras

2024-12-22 17:03 UTC, merged