feat: creacion modificar alumnos y mostrar las ternas
UNICAH-ICC-SAP/GestionPracticasWeb pull request #40
Opened 2024-12-13 08:10 UTC by Josue-rivas09

13.12.24: [FEATURE|BUGFIX] Se desarrollo la ventana de actualizar y borrar alumnos. Tambien se implemento la ventana de mostrar ternas

UNICAH-ICC-SAP/GestionPracticasWeb/issues/33

2024-12-13 15:04 UTC, Acalix-unicah requested changes
Atienda los cambios.

2024-12-13 15:04 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/modificarTernas/ModificarAlumno.tsx
> +            dispatch(FetcherAlumno.updatealumno(params))
El dispatch no se usa como una promesa. No Necesita THEN ni CATCH. Para eso es el store. para validar los cambios. Se rompe la estructura del proyecto.

2024-12-13 15:04 UTC, Acalix-unicah commented on src/components/shared/nav/menu.tsx
>              'title': 'Cargas Academicas',
Revise este componente, me aparece eliminación de lineas, esto introduce un bug.

2024-12-13 17:46 UTC, Josue-rivas09 commented
Con respecto al menu, se volvio a colocar como estaba antes para evitar errores, ya que por mi parte no hago uso de este

2024-12-13 18:16 UTC, Acalix-unicah requested changes
Atienda los cambios.

2024-12-13 18:16 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/modificarTernas/ModificarAlumno.tsx
> +            await dispatch(FetcherAlumno.getAlumnos(utils));
El dispatch no requiere de await, puede remover incluso el async de la linea 64. Revisar todos los casos.

2024-12-13 18:16 UTC, Acalix-unicah commented on src/pages/admin/crearTernas/modificarTernas/ModificarAlumno.tsx
> +            Swal.fire("¡Éxito!", "El alumno se ha actualizado exitosamente.", "success");
Se va a disparar el swal aunque no haya culminado el dispatch correctamente.

2024-12-14 05:38 UTC, Josue-rivas09 commented on src/pages/admin/crearTernas/modificarTernas/ModificarAlumno.tsx
> +            Swal.fire("¡Éxito!", "El alumno se ha actualizado exitosamente.", "success");
He reintroducido el uso de promesas debido a que, sin ellas, los cambios realizados al actualizar o eliminar un alumno no se reflejaban en la interfaz hasta que se recargaba manualmente la página. Además, con el uso de .then(), aseguro que el mensaje de éxito (Swal) se muestre únicamente después de que la operación de actualización o eliminación del alumno se haya completado correctamente.

2024-12-22 16:06 UTC, Acalix-unicah approved these changes
Deben hacerse mejoras de código.

2024-12-22 16:06 UTC, merged